"""Bilingual strings for the result figures and the manuscript.

Only the *labels* live here; every number still comes from the result JSON files,
so the English and Chinese versions cannot disagree numerically.
"""

from __future__ import annotations

LANG: dict[str, dict[str, str]] = {
    "en": {
        # Figure 1
        "fig1_physics": "Physics model\nAir/H/L/H/L/Glass\nTMM  $R(\\lambda)$",
        "fig1_data": "Dataset\n5,000 designs\n4000 / 500 / 500",
        "fig1_mlp": "MLP surrogate\n4-128-128-64-41\nMSE training",
        "fig1_screen": "Screening\n10,000 candidates\nrank at $\\lambda_{target}$",
        "fig1_final": "Top-10 verified by TMM\n$\\rightarrow$ final Top-5 design",
        "fig1_split": "fixed split, never re-shuffled",
        # Figure 2
        "fig2_title": "Air / H / L / H / L / Glass",
        "fig2_A": "(A) layer stack",
        "fig2_B": "(B) thickness sampling\n5,000 designs, uniform 40-180 nm",
        "fig2_C": "(C) TMM-generated spectra\n41 points, 400-800 nm",
        "fig2_x": "layer thickness  $d_i$ (nm)",
        "fig2_y": "count",
        "fig2_spec_x": "wavelength $\\lambda$ (nm)",
        "fig2_spec_y": "reflectance $R$",
        "fig2_sample": "sample",
        # Figure 3
        "fig3_input": "input\n$[d_1,d_2,d_3,d_4]$",
        "fig3_fc": "FC {n} + ReLU",
        "fig3_output": "output\n41 reflectance",
        "fig3_title": "MLP surrogate: thickness vector $\\rightarrow$ reflectance spectrum",
        "fig3_params": "\nlearnable parameters: {n:,}",
        "fig3_footer": "loss: MSE against TMM    optimiser: Adam    lr: {lr:g}    batch: {bs:d}    epochs: {ep:d}",
        # Figure 4
        "fig4_train": "training MSE",
        "fig4_val": "validation MSE",
        "fig4_best": "best epoch {n}",
        "fig4_x": "epoch",
        "fig4_y": "MSE (log scale)",
        "fig4_title": "Training and validation loss",
        # Figure 5
        "fig5_tmm": "TMM (reference)",
        "fig5_mlp": "MLP prediction",
        "fig5_x": "$\\lambda$ (nm)",
        "fig5_y": "reflectance $R$",
        "fig5_suptitle": "TMM vs MLP reflectance, {what}",
        "fig5_what": "representative test samples",
        # Figure 6
        "fig6_val": "validation MSE",
        "fig6_test": "test MSE",
        "fig6_xt": "number of training samples",
        "fig6_y": "MSE",
        "fig6_tA": "(A) test and validation MSE",
        "fig6_vr": "validation RMSE",
        "fig6_tr": "test RMSE",
        "fig6_xtl": "number of training samples (log scale)",
        "fig6_yr": "RMSE",
        "fig6_tB": "(B) error versus data volume",
        # Figure 7
        "fig7_cand_t": "TMM, finalists",
        "fig7_cand_m": "MLP, finalists",
        "fig7_sel_t": "TMM, selected design",
        "fig7_sel_m": "MLP, selected design",
        "fig7_x": "wavelength $\\lambda$ (nm)",
        "fig7_y": "reflectance $R$",
        "fig7_tA": "(A) selected design and the five finalists",
        "fig7_parity": "parity $y=x$",
        "fig7_xp": "MLP $R(\\lambda_{target})$",
        "fig7_yp": "TMM $R(\\lambda_{target})$",
        "fig7_tB": "(B) MLP ranking verified by TMM",
        # Figure 8
        "fig8_worst": "worst test sample\n$d$ = [{d0:.0f}, {d1:.0f}, {d2:.0f}, {d3:.0f}] nm",
        "fig8_err": "prediction error\nMSE = {mse:.2e}",
        "fig8_dist": "error distribution over the 500 test samples",
        "fig8_median": "median {med:.2e}",
        "fig8_this": "this sample (rank {rank}/{total})",
        "fig8_rank": "test-sample rank",
        "fig8_perms": "per-sample MSE",
        "fig8_err_y": "$R_{MLP} - R_{TMM}$",
    },
    "zh": {
        "fig1_physics": "物理模型\nAir/H/L/H/L/Glass\nTMM  $R(\\lambda)$",
        "fig1_data": "数据集\n5000 组设计\n4000 / 500 / 500",
        "fig1_mlp": "MLP 代理模型\n4-128-128-64-41\nMSE 训练",
        "fig1_screen": "候选筛选\n10000 组候选\n按 $\\lambda_{target}$ 排序",
        "fig1_final": "Top-10 用 TMM 复算\n$\\rightarrow$ 最终 Top-5 设计",
        "fig1_split": "划分固定，不再打乱",
        "fig2_title": "Air / H / L / H / L / Glass",
        "fig2_A": "(A) 膜系结构",
        "fig2_B": "(B) 膜厚采样分布\n5000 组，40–180 nm 均匀分布",
        "fig2_C": "(C) TMM 生成的光谱\n41 个波长点，400–800 nm",
        "fig2_x": "膜层厚度  $d_i$ (nm)",
        "fig2_y": "计数",
        "fig2_spec_x": "波长 $\\lambda$ (nm)",
        "fig2_spec_y": "反射率 $R$",
        "fig2_sample": "样本",
        "fig3_input": "输入\n$[d_1,d_2,d_3,d_4]$",
        "fig3_fc": "全连接 {n} + ReLU",
        "fig3_output": "输出\n41 点反射光谱",
        "fig3_title": "MLP 代理模型：膜厚向量 $\\rightarrow$ 反射光谱",
        "fig3_params": "\n可训练参数：{n:,}",
        "fig3_footer": "损失：对 TMM 的 MSE    优化器：Adam    学习率：{lr:g}    批大小：{bs:d}    轮数：{ep:d}",
        "fig4_train": "训练 MSE",
        "fig4_val": "验证 MSE",
        "fig4_best": "最优轮次 {n}",
        "fig4_x": "训练轮次",
        "fig4_y": "MSE（对数坐标）",
        "fig4_title": "训练与验证损失",
        "fig5_tmm": "TMM（参考）",
        "fig5_mlp": "MLP 预测",
        "fig5_x": "$\\lambda$ (nm)",
        "fig5_y": "反射率 $R$",
        "fig5_suptitle": "TMM 与 MLP 反射光谱对比（{what}）",
        "fig5_what": "代表性测试样本",
        "fig6_val": "验证 MSE",
        "fig6_test": "测试 MSE",
        "fig6_xt": "训练样本数",
        "fig6_y": "MSE",
        "fig6_tA": "(A) 测试与验证 MSE",
        "fig6_vr": "验证 RMSE",
        "fig6_tr": "测试 RMSE",
        "fig6_xtl": "训练样本数（对数坐标）",
        "fig6_yr": "RMSE",
        "fig6_tB": "(B) 误差随数据量的变化",
        "fig7_cand_t": "TMM，入选候选",
        "fig7_cand_m": "MLP，入选候选",
        "fig7_sel_t": "TMM，选定设计",
        "fig7_sel_m": "MLP，选定设计",
        "fig7_x": "波长 $\\lambda$ (nm)",
        "fig7_y": "反射率 $R$",
        "fig7_tA": "(A) 选定设计与五个入选候选",
        "fig7_parity": "对角线 $y=x$",
        "fig7_xp": "MLP $R(\\lambda_{target})$",
        "fig7_yp": "TMM $R(\\lambda_{target})$",
        "fig7_tB": "(B) MLP 排序经 TMM 验证",
        "fig8_worst": "测试集最差样本\n$d$ = [{d0:.0f}, {d1:.0f}, {d2:.0f}, {d3:.0f}] nm",
        "fig8_err": "预测误差\nMSE = {mse:.2e}",
        "fig8_dist": "500 个测试样本的误差分布",
        "fig8_median": "中位数 {med:.2e}",
        "fig8_this": "本样本（排名 {rank}/{total}）",
        "fig8_rank": "测试样本排名",
        "fig8_perms": "单样本 MSE",
        "fig8_err_y": "$R_{MLP} - R_{TMM}$",
    },
}


def t(key: str, lang: str = "en", **kw) -> str:
    s = LANG[lang][key]
    return s.format(**kw) if kw else s
